# Generated by Django 6.0.3 on 2026-03-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100, null=True)),
                ('engine', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('dimmenssion', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tank', models.DecimalField(decimal_places=2, max_digits=3)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=3)),
                ('external_color', models.CharField(max_length=100, null=True)),
                ('internal_color', models.CharField(max_length=100, null=True)),
                ('availability', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
